# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
imageBackend: soniamahankali/webapp-backend:latest
imageFrontend: soniamahankali/webapp-frontend:latest
databaseUrl: db1.cr0cwfqbfpxp.us-east-1.rds.amazonaws.com
bucketUrl: k8s.dev.soniamahankali.com
imagePullSecrets: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7ImF1dGgiOiAiYzI5dWFXRnRZV2hoYm10aGJHazZTVzFqYUdGdGNESTAifQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjUgKGRhcndpbikiCgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiZXhwZXJpbWVudGFsIjogImRpc2FibGVkIiwKCSJzdGFja09yY2hlc3RyYXRvciI6ICJzd2FybSIKfQo=
redis:
  password: "password"
redisPort: 6379
initContainers:
  name: busybox:1.28
image:
  name: |
    soniamahankali/webapp-backend:2be6b44201afcb69be90d8606ff92ed86e94c08e
