apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer-api
  namespace: api
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer