---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  namespace: ui
  labels:
    app: ui
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      initContainers:
        - name: init-cotainer-ui
          image: {{ .Values.initContainers.name }}
          command:
            - 'sh'
            - '-c'
            - >
              until nslookup {{ .Release.Name }}-load-balancer-ui.ui ;
                do echo waiting for myservice;
                sleep 60;
              done;

      containers:
      - name: ui
        image: {{ .Values.imageFrontend }}
        ports:
          - name: live-port
            containerPort: 3000
        resources:
          requests:
            memory: "8Mi"
            cpu: "1m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
      imagePullSecrets:
      - name: {{ .Release.Name }}-registrykey
      