apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registrykey
  namespace: api
  namespace: ui
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets }}
type: kubernetes.io/dockerconfigjson