apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer-api
  namespace: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer